### ISSUE TITLE
Add ignore Folder First for a Bookmarks Bar

### ISSUE THREAD

**Issue by AlexByte** [ForestMist/sprucemarks#11]

**Comment by ForestMist** [comment]
I like the simplicity of an overall folder first setting that affects everything vs. having individual settings per area.

I keep my bookmarks bar pretty tidy and just the way I want it by having the sorting option unchecked. I also like having every other area checked for sorting and those other areas are of course affected by the folder first option.

Anyway, long story short, no plans to implement per area folder sorting options.
