### ISSUE TITLE
Switch from localStrorage to chrome.storage

### ISSUE THREAD

**Issue by AlexByte** [ForestMist/sprucemarks#12]
I periodically lose the settings in all extensions using localStrorage.

**Comment by ForestMist** [comment]
Thanks for the idea. Will investigate. No ETA as of yet though. Work and such.

**Comment by ForestMist** [comment]
I have a build that uses chrome.storage instead of localStorage and it seems like it might work out. Going to run it through a battery of tests (upgrade, new install, all option variants) to make sure it works. Will let you know.

**Comment by ForestMist** [comment]
New version is live here on GitHub and in the process of being published on the Chrome Web Store. If you are using the Chrome Web Store version you should be upgraded automatically. Supposedly within 5 hours but I've seen it take longer.

Hopefully whatever event was clobbering your localStorage won't be able to touch your Sprucemarks options now. ^_^

Thanks for this issue and your patience. ^_^
