### ISSUE TITLE
Suggetion: exclude folders from sorting

### ISSUE THREAD

**Issue by HaderOfSweden** [ForestMist/sprucemarks#13]
I would like to suggest an option to exclude folders from getting sorted.
Here is an example of how I would use it: I have a folder called "go through" where I add stuff, to go through later. By leaving them unsorted, I can easily find something I added recently or before that. But if they are ordered, then its hard to quickly find what I am looking for.

**Thank you**

**Comment by ForestMist** [comment]
Use case is completely logical. Unfortunately Sprucemarks is in maintenance mode at this point in its life. As in I do not wish to add any complexity to the behind the scenes code or the user facing options page. Just bug fixes going forward.

Sorry Hader.

**Comment by HaderOfSweden** [comment]
Thank you anyway.
I think there might be a workaround by adding the non-sorted in mobile bookmarks...
