### ISSUE TITLE
Sorting not happening after edit

### ISSUE THREAD

**Issue by tobyhoward** [ForestMist/sprucemarks#16]
Hi Daniel, 

First, thanks for Sprucemarks, I love it. I noticed that when using Bookmark Manager to manually copy bookmarks from bookmarks folder X, and paste into folder Y, the bookmarks incoming to folder Y are not getting sorted. So Y is now a mixture of its original sorted self, and unsorted incoming.

best wishes
Toby

**Comment by ForestMist** [comment]
Yay, you are welcome. ^_^

Can you give me some more details on exactly where and how you are copying bookmarks? I tried dragging and dropping a bookmark and that sorted for me but perhaps I can experience the same issue if you guide me towards recreating it.

**Comment by ForestMist** [comment]
Ah, I didn't realize you could use copy and paste shortcuts. Neat.

I tried the same procedure, copying from a folder with no sorting, to a folder with sorting. After about 1 second, the copied bookmark in the destination folder was sorted.

If you look at your Sprucemarks options and go all the way to the bottom, is the "Delay Sorting of New Bookmarks" option checked? If yes, can you uncheck it, click "Save", and then try the same copy/paste bookmark procedure?

**Comment by tobyhoward** [comment]
Hi Daneil

Yes, if that's unchecked it seems fine! Thanks and sorry of I have wasted your time with this!

best,
Toby

--
Toby Howard
Reader, Director of Undergraduate Studies
School of Computer Science, The University of Manchester, UK
www.cs.man.ac.uk/~toby

________________________________

**Comment by ForestMist** [comment]
Oh no, not a waste at all. You taught me you could use copy/paste and it sounds like without that option turned on, it works better for you. ^_^

Cheers!
