### ISSUE TITLE
Folders not sorting like bookmarks

### ISSUE THREAD

**Issue by CouranaDesign** [ForestMist/sprucemarks#17]
Hello!  I'm loving your SpruceMarks addon, using it to sort bookmarks by date added.  I noticed, however, that when I organize using the "newer to older" setting, folders seem to be organized in the opposite direction (older to newer).  In addition, the folders are grouped up, even if their internal "date added" or "date modified" timestamps would normally dictate that they be interspersed with individual bookmarks.  Is there any chance these issues could be addressed?  Or am I doing something wrong?

**Comment by ForestMist** [comment]
Under your Sprucemarks options, do you have "Folders First" checked or unchecked? If it is checked and you uncheck it and then hit save, does the date sorting work better on folders?
