### ISSUE TITLE
Have to shut down and reopen chrome for sorting to happen

### ISSUE THREAD

**Issue by aa3993** [ForestMist/sprucemarks#8]
After I brake the sorted condition by using chrome's own sorter, I have to reopen chrome for it to be sorted again, would be better if there were loop running in a thread that continuosly sorts. As a side note my sorting delay is disabled if its related.

**Comment by ForestMist** [comment]
Interesting. Which sorting option are you using that comes with Chrome? Can you describe to me how I can get to that same location to try it?

As long as there are not other sorting extensions being run, Sprucemarks should run in a loop and keep everything tidy.

**Comment by aa3993** [comment]
Here, chrome://bookmarks/ then Organize > Reorder by Title

**Comment by ForestMist** [comment]
Sorry for the delay.

I'm having trouble recreating the issue. I changed my Sprucemarks sorting option to Alpha Z-A for my "Bookmarks Bar" and then I used Chrome's own Organize -> "Reorder by Title". The bookmarks quickly jump into Chrome's order and then quickly jump back to the Sprucemarks order. This is how it should work ideally.

It sounds like using the Organize -> "Reorder by Title" feature of Chrome always stops your Sprucemarks from sorting? Or does it only happen some of the time?

**Comment by aa3993** [comment]
well it still does but i came to the conclusion that it is an extremely minor bug and on top of that in some instances it is better for it to be delayed until you disorganize it (change the ordering of one site from the list). you can close this issue for that reason.
